Revert "perf bench: Add futex2 benchmark tests"
Doesn't build with Debian Liquorix kernel package:

In file included from bench/futex-hash.c:28:
bench/futex.h:129:50: error: 'struct futex_requeue' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
 static inline int futex2_requeue(volatile struct futex_requeue *uaddr1,
                                                  ^~~~~~~~~~~~~
dh_testdir
bench/futex-hash.c: In function '__bench_futex_hash':
bench/futex-hash.c:155:16: error: 'FUTEX_32' undeclared (first use in this function); did you mean 'FUTEX_OP'?
   futex_flag = FUTEX_32 | (fshared * FUTEX_SHARED_FLAG);
                ^~~~~~~~
                FUTEX_OP
bench/futex-hash.c:155:16: note: each undeclared identifier is reported only once for each function it appears in
bench/futex-hash.c:155:38: error: 'FUTEX_SHARED_FLAG' undeclared (first use in this function); did you mean 'FUTEX_PRIVATE_FLAG'?
   futex_flag = FUTEX_32 | (fshared * FUTEX_SHARED_FLAG);
                                      ^~~~~~~~~~~~~~~~~
                                      FUTEX_PRIVATE_FLAG

This reverts commit 3f97b7c7565bd90a96d9549190122fe05f4ed468.